name: Voe tester

on:
    workflow_dispatch:

jobs:
    run-python-script:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar el repositorio
              uses: actions/checkout@v4

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            
            - name: Instalar dependencias
              run: pip install -r requirements.txt

            - name: Ejecutar script
              env: 
                  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  API_KEY_VOE: ${{ secrets.API_KEY_VOE }}
                  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
                  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
                  CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
              run: python src/monitor/test_voe.py

            - name: Subir archivo de fallas
              uses: actions/upload-artifact@v4
              with:
                  name: fallas
                  path: fallas.md
